# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jonas Viehweger
subtitle: Portfolio
author: Jonas Viehweger
email: Viehwege@students.uni-marburg.de
description: >- # this means to ignore newlines until "baseurl:"
  Remote Sensing and Geospatial Analysis in R, Python and Earth Engine. Past projects and analysis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
avatar: assets/ava_48x48.jpg

# Social settings
twitter_url: https://twitter.com/jviehweger2
github_url: https://github.com/jonasViehweger
# linkedin_url: 
# instagram_url: 


# Build settings
# theme: jekyll-theme-prologue
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-feed

collections: [sections]

# Theme Settings
order: 1
cover-photo: assets/banner.jpg
cover-photo-alt: Sentinel-2 acquisition off the coast of South Korea
icon: fa-infinity
icon-style: light

# Google Analytics Tracking ID goes here:
google_analytics: 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
